// =====================================================================
// CES Tech internal tool — Azure infrastructure (Batch 3)
//
// One template, one resource group. Spins up:
//   - Log Analytics Workspace      (logs from Container Apps + App Insights later)
//   - Azure Database for PostgreSQL Flexible Server (B-tier, Central India)
//   - Key Vault                    (secrets that the API + web need at runtime)
//   - Storage Account              (receipts container, blob, hot tier)
//   - Container Apps Environment   (consumption plan)
//   - Container App: API           (NestJS, pulls image from GHCR)
//   - Container App: Web           (Next.js standalone, pulls image from GHCR)
//
// Deploy with infra/deploy.sh — it handles parameter prompts + post-deploy
// outputs + smoke test. Do NOT run `az deployment group create` by hand
// without reading deploy.sh first.
// =====================================================================

targetScope = 'resourceGroup'

@description('Short environment slug: prod | staging | dev')
@allowed(['dev', 'staging', 'prod'])
param env string = 'prod'

@description('Azure region. Locked to centralindia for data residency.')
@allowed(['centralindia', 'southindia'])
param location string = 'centralindia'

@description('Postgres admin username. Must NOT be "postgres", "azure_superuser", or any reserved keyword.')
param pgAdminUser string = 'cesadmin'

@description('Postgres admin password — generated by deploy.sh, never committed.')
@secure()
param pgAdminPassword string

@description('Image tag to deploy. Use a sha-<short> tag from GHCR for reproducibility; "latest" for follow-main.')
param apiImageTag string = 'latest'

@description('Image tag for the web app — same convention as apiImageTag.')
param webImageTag string = 'latest'

@description('GHCR owner (GitHub user / org that hosts the images).')
param ghcrOwner string = 'ciscosoni'

@description('Anthropic API key. Optional — when blank the AI flows fall back to the mock. Stored in Key Vault.')
@secure()
param anthropicApiKey string = ''

@description('Until Batch 4 wires Entra ID, the auth guard returns 401 by default. Set to true to allow the dev-header path on this deployment. NEVER share the URL publicly while this is true.')
param allowDevAuthInProd bool = true

// -----------------------------------------------------------------------------
// Naming
// -----------------------------------------------------------------------------
// Most Azure resources require globally-unique names — we suffix everything
// with a hash of the resource-group ID. Storage accounts + Key Vault have
// the tightest character + length constraints.
var rgHash = uniqueString(resourceGroup().id)
var namePrefix = 'ces-${env}'
var workspaceName = '${namePrefix}-logs'
var keyVaultName = take('cesvault${env}${rgHash}', 24)
var storageAccountName = take('cesst${env}${rgHash}', 24)
var pgServerName = '${namePrefix}-pg-${rgHash}'
var pgDatabaseName = 'ces'
var environmentName = '${namePrefix}-cae'
var apiAppName = '${namePrefix}-api'
var webAppName = '${namePrefix}-web'

// -----------------------------------------------------------------------------
// Log Analytics — destination for Container App console logs
// -----------------------------------------------------------------------------
resource workspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {
  name: workspaceName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
  }
}

// -----------------------------------------------------------------------------
// Storage Account — receipt blob container (filled by Batch 4 mobile flow)
// -----------------------------------------------------------------------------
resource storage 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageAccountName
  location: location
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
    publicNetworkAccess: 'Enabled'
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: storage
  name: 'default'
  properties: {}
}

resource receiptsContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: 'receipts'
  properties: {
    publicAccess: 'None'
  }
}

// -----------------------------------------------------------------------------
// PostgreSQL Flexible Server — B-tier Burstable for low-cost first deploy
// -----------------------------------------------------------------------------
// B1ms: ~$25/mo + ~$5/mo storage. Move to a General Purpose D-series later
// when load justifies it. Geo-redundant backup is OFF for the same reason —
// flip on once the tool is mission-critical.
resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2023-12-01-preview' = {
  name: pgServerName
  location: location
  sku: {
    name: 'Standard_B1ms'
    tier: 'Burstable'
  }
  properties: {
    version: '16'
    administratorLogin: pgAdminUser
    administratorLoginPassword: pgAdminPassword
    storage: {
      storageSizeGB: 32
      autoGrow: 'Enabled'
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
    network: {
      // Public access with explicit firewall rules — simplest for Batch 3.
      // Batch 5 considers a VNet-injected private endpoint + Private DNS zone
      // when the tool has real users and the surface area matters more.
      publicNetworkAccess: 'Enabled'
    }
  }
}

// Allow all Azure-internal services. Container Apps egress IPs vary per
// replica and per scale event, so explicit IP allowlisting is impractical
// at this size. Combined with strong auth and TLS, this is acceptable.
resource pgFirewallAzureServices 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2023-12-01-preview' = {
  parent: pg
  name: 'AllowAllAzureServices'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

resource pgDatabase 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-12-01-preview' = {
  parent: pg
  name: pgDatabaseName
  properties: {
    charset: 'UTF8'
    collation: 'en_US.utf8'
  }
}

// -----------------------------------------------------------------------------
// Key Vault — runtime secrets (DB URL, anthropic key, future Entra secret)
// -----------------------------------------------------------------------------
// RBAC authorization mode so Container App managed identities can read
// secrets via a single role assignment.
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    tenantId: subscription().tenantId
    sku: {
      family: 'A'
      name: 'standard'
    }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 30
    publicNetworkAccess: 'Enabled'
  }
}

var pgConnectionString = 'postgresql://${pgAdminUser}:${uriComponent(pgAdminPassword)}@${pg.properties.fullyQualifiedDomainName}:5432/${pgDatabaseName}?sslmode=require'

resource kvDatabaseUrl 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'database-url'
  properties: {
    value: pgConnectionString
  }
}

// Always create the KV secret. When the caller didn't supply a key, store the
// sentinel value `_unset_` — the API's AiService treats anything that doesn't
// start with `sk-ant-` as unconfigured and falls back to the deterministic
// mock. This keeps the Container App env wiring unconditional.
resource kvAnthropicKey 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'anthropic-api-key'
  properties: {
    value: empty(anthropicApiKey) ? '_unset_' : anthropicApiKey
  }
}

resource kvStorageConnection 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'storage-connection-string'
  properties: {
    value: 'DefaultEndpointsProtocol=https;AccountName=${storage.name};AccountKey=${storage.listKeys().keys[0].value};EndpointSuffix=${environment().suffixes.storage}'
  }
}

// -----------------------------------------------------------------------------
// Container Apps — managed env + 2 apps with user-assigned managed identity
// -----------------------------------------------------------------------------
resource managedEnvironment 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: environmentName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: workspace.properties.customerId
        sharedKey: workspace.listKeys().primarySharedKey
      }
    }
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
    zoneRedundant: false
  }
}

// User-assigned managed identity shared by both Container Apps. Lets us
// scope a single Key Vault Secrets User role assignment instead of two.
resource sharedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: '${namePrefix}-app-mi'
  location: location
}

// Built-in role: Key Vault Secrets User
var kvSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'
resource kvRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: keyVault
  name: guid(keyVault.id, sharedIdentity.id, kvSecretsUserRoleId)
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', kvSecretsUserRoleId)
    principalId: sharedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource apiApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: apiAppName
  location: location
  dependsOn: [
    kvRoleAssignment
    pgDatabase
  ]
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${sharedIdentity.id}': {}
    }
  }
  properties: {
    managedEnvironmentId: managedEnvironment.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 4000
        transport: 'auto'
        allowInsecure: false
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
      }
      secrets: [
        {
          name: 'database-url'
          keyVaultUrl: '${keyVault.properties.vaultUri}secrets/database-url'
          identity: sharedIdentity.id
        }
        {
          name: 'storage-connection-string'
          keyVaultUrl: '${keyVault.properties.vaultUri}secrets/storage-connection-string'
          identity: sharedIdentity.id
        }
        {
          name: 'anthropic-api-key'
          keyVaultUrl: '${keyVault.properties.vaultUri}secrets/anthropic-api-key'
          identity: sharedIdentity.id
        }
      ]
    }
    template: {
      containers: [
        {
          name: 'api'
          image: 'ghcr.io/${ghcrOwner}/ces-api:${apiImageTag}'
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
          env: [
            { name: 'NODE_ENV', value: 'production' }
            { name: 'API_PORT', value: '4000' }
            { name: 'LOG_LEVEL', value: 'info' }
            { name: 'APP_VERSION', value: apiImageTag }
            { name: 'ALLOW_DEV_AUTH_IN_PROD', value: string(allowDevAuthInProd) }
            { name: 'DEV_AUTH_DEFAULT_EMAIL', value: 'admin@cestech.in' }
            { name: 'RUN_MIGRATIONS', value: 'true' }
            // Entra ID placeholders — Batch 4 swaps these out for real
            // App-Registration values + flips the auth guard.
            { name: 'AZURE_TENANT_ID', value: '00000000-0000-0000-0000-000000000000' }
            { name: 'AZURE_API_CLIENT_ID', value: '00000000-0000-0000-0000-000000000000' }
            { name: 'AZURE_API_AUDIENCE', value: 'api://ces-internal' }
            { name: 'AZURE_STORAGE_ACCOUNT', value: storage.name }
            { name: 'AZURE_STORAGE_CONTAINER', value: 'receipts' }
            { name: 'AZURE_STORAGE_CONNECTION_STRING', secretRef: 'storage-connection-string' }
            { name: 'ANTHROPIC_API_KEY', secretRef: 'anthropic-api-key' }
            { name: 'ANTHROPIC_MODEL', value: 'claude-opus-4-7' }
            { name: 'DATABASE_URL', secretRef: 'database-url' }
          ]
          probes: [
            {
              type: 'Liveness'
              httpGet: { path: '/api/health', port: 4000 }
              initialDelaySeconds: 20
              periodSeconds: 30
              failureThreshold: 3
            }
            {
              type: 'Readiness'
              httpGet: { path: '/api/ready', port: 4000 }
              initialDelaySeconds: 25
              periodSeconds: 15
              failureThreshold: 3
            }
            {
              type: 'Startup'
              httpGet: { path: '/api/health', port: 4000 }
              initialDelaySeconds: 10
              periodSeconds: 5
              failureThreshold: 30
              timeoutSeconds: 5
            }
          ]
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 3
        rules: [
          {
            name: 'http-concurrency'
            http: {
              metadata: {
                concurrentRequests: '50'
              }
            }
          }
        ]
      }
    }
  }
}

resource webApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: webAppName
  location: location
  dependsOn: [
    apiApp
  ]
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${sharedIdentity.id}': {}
    }
  }
  properties: {
    managedEnvironmentId: managedEnvironment.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 3000
        transport: 'auto'
        allowInsecure: false
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
      }
    }
    template: {
      containers: [
        {
          name: 'web'
          image: 'ghcr.io/${ghcrOwner}/ces-web:${webImageTag}'
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
          env: [
            { name: 'NODE_ENV', value: 'production' }
            { name: 'PORT', value: '3000' }
            // The web app's server side talks to the API over the public
            // Container Apps FQDN. API_BASE_URL is read at RUNTIME (NEXT_PUBLIC_*
            // gets frozen into the bundle at build time, so it can't be changed
            // here); this is the one the server actually uses. Batch 5 swaps
            // these for the api.ops.ces-pl.com custom domain once the cert
            // binding is in place — just an env update, no image rebuild.
            { name: 'API_BASE_URL', value: 'https://${apiApp.properties.configuration.ingress.fqdn}' }
            { name: 'NEXT_PUBLIC_API_BASE_URL', value: 'https://${apiApp.properties.configuration.ingress.fqdn}' }
          ]
          probes: [
            {
              type: 'Liveness'
              httpGet: { path: '/login', port: 3000 }
              initialDelaySeconds: 20
              periodSeconds: 30
              failureThreshold: 3
            }
          ]
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 3
        rules: [
          {
            name: 'http-concurrency'
            http: {
              metadata: {
                concurrentRequests: '50'
              }
            }
          }
        ]
      }
    }
  }
}

// -----------------------------------------------------------------------------
// Outputs — deploy.sh consumes these to print the URLs + next steps
// -----------------------------------------------------------------------------
output apiUrl string = 'https://${apiApp.properties.configuration.ingress.fqdn}'
output webUrl string = 'https://${webApp.properties.configuration.ingress.fqdn}'
output keyVaultName string = keyVault.name
output postgresFqdn string = pg.properties.fullyQualifiedDomainName
output postgresDatabase string = pgDatabaseName
output storageAccountName string = storage.name
output logAnalyticsWorkspace string = workspace.name
output managedIdentityClientId string = sharedIdentity.properties.clientId
